//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TesteDBEntities : DbContext
    {
        public TesteDBEntities()
            : base("name=TesteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Capitole> t_Capitole { get; set; }
        public virtual DbSet<t_Conturi> t_Conturi { get; set; }
        public virtual DbSet<t_Dificultati> t_Dificultati { get; set; }
        public virtual DbSet<t_Domenii> t_Domenii { get; set; }
        public virtual DbSet<t_DomeniiAdministratori> t_DomeniiAdministratori { get; set; }
        public virtual DbSet<t_InformatiiRezultate> t_InformatiiRezultate { get; set; }
        public virtual DbSet<t_Intrebari> t_Intrebari { get; set; }
        public virtual DbSet<t_IntrebariRezultate> t_IntrebariRezultate { get; set; }
        public virtual DbSet<t_Parole> t_Parole { get; set; }
        public virtual DbSet<t_Rezultate> t_Rezultate { get; set; }
        public virtual DbSet<t_TexteVariante> t_TexteVariante { get; set; }
        public virtual DbSet<t_Variante> t_Variante { get; set; }
    }
}
