//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Capitole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Capitole()
        {
            this.t_InformatiiRezultate = new HashSet<t_InformatiiRezultate>();
            this.t_Intrebari = new HashSet<t_Intrebari>();
        }
    
        public int ID_Capitol { get; set; }
        public string Capitol { get; set; }
        public int ID_Domeniu { get; set; }
    
        public virtual t_Domenii t_Domenii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_InformatiiRezultate> t_InformatiiRezultate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Intrebari> t_Intrebari { get; set; }
    }
}
