//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Conturi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Conturi()
        {
            this.t_DomeniiAdministratori = new HashSet<t_DomeniiAdministratori>();
            this.t_InformatiiRezultate = new HashSet<t_InformatiiRezultate>();
        }
    
        public int ID_Cont { get; set; }
        public string Nume { get; set; }
        public int ID_Parola { get; set; }
        public byte[] ImagineProfil { get; set; }
    
        public virtual t_Parole t_Parole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_DomeniiAdministratori> t_DomeniiAdministratori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_InformatiiRezultate> t_InformatiiRezultate { get; set; }
    }
}
