//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DomeniiAdministratori
    {
        public int ID_DomeniuAdministrator { get; set; }
        public int ID_ContAdministrator { get; set; }
        public int ID_Domeniu { get; set; }
    
        public virtual t_Conturi t_Conturi { get; set; }
        public virtual t_Domenii t_Domenii { get; set; }
    }
}
