//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_InformatiiRezultate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_InformatiiRezultate()
        {
            this.t_Rezultate = new HashSet<t_Rezultate>();
        }
    
        public int ID_InformatiiRezultat { get; set; }
        public int ID_Cont { get; set; }
        public int ID_Capitol { get; set; }
        public double Punctaj { get; set; }
        public int Nivel { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual t_Capitole t_Capitole { get; set; }
        public virtual t_Conturi t_Conturi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Rezultate> t_Rezultate { get; set; }
    }
}
