//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Intrebari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Intrebari()
        {
            this.t_IntrebariRezultate = new HashSet<t_IntrebariRezultate>();
        }
    
        public int ID_Intrebare { get; set; }
        public string EnuntIntrebare { get; set; }
        public int ID_Varianta1 { get; set; }
        public int ID_Varianta2 { get; set; }
        public int ID_Varianta3 { get; set; }
        public int ID_Varianta4 { get; set; }
        public int ID_Capitol { get; set; }
        public int ID_Dificultate { get; set; }
        public byte[] Imagine { get; set; }
        public bool Stearsa { get; set; }
    
        public virtual t_Capitole t_Capitole { get; set; }
        public virtual t_Dificultati t_Dificultati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_IntrebariRezultate> t_IntrebariRezultate { get; set; }
        public virtual t_Variante t_Variante { get; set; }
        public virtual t_Variante t_Variante1 { get; set; }
        public virtual t_Variante t_Variante2 { get; set; }
        public virtual t_Variante t_Variante3 { get; set; }
    }
}
