//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_IntrebariRezultate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_IntrebariRezultate()
        {
            this.t_Rezultate = new HashSet<t_Rezultate>();
        }
    
        public int ID_IntrebareRezultat { get; set; }
        public int ID_Intrebare { get; set; }
        public bool Raspuns1 { get; set; }
        public bool Raspuns2 { get; set; }
        public bool Raspuns3 { get; set; }
        public bool Raspuns4 { get; set; }
    
        public virtual t_Intrebari t_Intrebari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Rezultate> t_Rezultate { get; set; }
    }
}
